name: Docker base container for VRE ops build

# Build image with changes to any file within containers/base-ops/
# and when a new tag is created.
on:
  push:
    paths:
      - containers/base-ops/**
    tags:
      - '**'

env:
  CONTAINER: base-ops
  # Use docker.io for Docker Hub if empty
  REGISTRY: ghcr.io
  # github.repository as <account>/<repo>
  IMAGE_NAME: ${{ github.repository }}-$CONTAINER


jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        working-directory: containers/base-ops
        run: |
          docker build . --tag  ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          docker push  ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          git clone https://github.com/vre-hub/vre.git
          cd vre
          # Echo the output, substitute the `-g` with a `-` and export the result.
          # The `-g` is by default on git describe because of historical reasons.
          echo "tag_describe=$(git describe --tags | sed 's/-g/-/g')"
          export tag_describe=$(git describe --tags | sed 's/-g/-/g')
          cd ..
          docker tag ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${tag_describe}
          docker push  ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${tag_describe}
          rm -rf vre
          